// source: api_options.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = (function() { return this || window || global || self || Function('return this')(); }).call(null);

var google_protobuf_descriptor_pb = require('google-protobuf/google/protobuf/descriptor_pb.js');
goog.object.extend(proto, google_protobuf_descriptor_pb);
goog.exportSymbol('proto.APISourceType', null, global);
goog.exportSymbol('proto.id', null, global);
goog.exportSymbol('proto.ifdef', null, global);
goog.exportSymbol('proto.log', null, global);
goog.exportSymbol('proto.needsAuthentication', null, global);
goog.exportSymbol('proto.needsSetupConnection', null, global);
goog.exportSymbol('proto.noDelay', null, global);
goog.exportSymbol('proto.source', null, global);
goog.exportSymbol('proto.void', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.void = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.void, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.void.displayName = 'proto.void';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.void.prototype.toObject = function(opt_includeInstance) {
  return proto.void.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.void} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.void.toObject = function(includeInstance, msg) {
  var f, obj = {

  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.void}
 */
proto.void.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.void;
  return proto.void.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.void} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.void}
 */
proto.void.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.void.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.void.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.void} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.void.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
};


/**
 * @enum {number}
 */
proto.APISourceType = {
  SOURCE_BOTH: 0,
  SOURCE_SERVER: 1,
  SOURCE_CLIENT: 2
};


/**
 * A tuple of {field number, class constructor} for the extension
 * field named `needsSetupConnection`.
 * @type {!jspb.ExtensionFieldInfo<boolean>}
 */
proto.needsSetupConnection = new jspb.ExtensionFieldInfo(
    1038,
    {needsSetupConnection: 0},
    null,
     /** @type {?function((boolean|undefined),!jspb.Message=): !Object} */ (
         null),
    0);

google_protobuf_descriptor_pb.MethodOptions.extensionsBinary[1038] = new jspb.ExtensionFieldBinaryInfo(
    proto.needsSetupConnection,
    jspb.BinaryReader.prototype.readBool,
    jspb.BinaryWriter.prototype.writeBool,
    undefined,
    undefined,
    false);
// This registers the extension field with the extended class, so that
// toObject() will function correctly.
google_protobuf_descriptor_pb.MethodOptions.extensions[1038] = proto.needsSetupConnection;


/**
 * A tuple of {field number, class constructor} for the extension
 * field named `needsAuthentication`.
 * @type {!jspb.ExtensionFieldInfo<boolean>}
 */
proto.needsAuthentication = new jspb.ExtensionFieldInfo(
    1039,
    {needsAuthentication: 0},
    null,
     /** @type {?function((boolean|undefined),!jspb.Message=): !Object} */ (
         null),
    0);

google_protobuf_descriptor_pb.MethodOptions.extensionsBinary[1039] = new jspb.ExtensionFieldBinaryInfo(
    proto.needsAuthentication,
    jspb.BinaryReader.prototype.readBool,
    jspb.BinaryWriter.prototype.writeBool,
    undefined,
    undefined,
    false);
// This registers the extension field with the extended class, so that
// toObject() will function correctly.
google_protobuf_descriptor_pb.MethodOptions.extensions[1039] = proto.needsAuthentication;


/**
 * A tuple of {field number, class constructor} for the extension
 * field named `id`.
 * @type {!jspb.ExtensionFieldInfo<number>}
 */
proto.id = new jspb.ExtensionFieldInfo(
    1036,
    {id: 0},
    null,
     /** @type {?function((boolean|undefined),!jspb.Message=): !Object} */ (
         null),
    0);

google_protobuf_descriptor_pb.MessageOptions.extensionsBinary[1036] = new jspb.ExtensionFieldBinaryInfo(
    proto.id,
    jspb.BinaryReader.prototype.readUint32,
    jspb.BinaryWriter.prototype.writeUint32,
    undefined,
    undefined,
    false);
// This registers the extension field with the extended class, so that
// toObject() will function correctly.
google_protobuf_descriptor_pb.MessageOptions.extensions[1036] = proto.id;


/**
 * A tuple of {field number, class constructor} for the extension
 * field named `source`.
 * @type {!jspb.ExtensionFieldInfo<!proto.APISourceType>}
 */
proto.source = new jspb.ExtensionFieldInfo(
    1037,
    {source: 0},
    null,
     /** @type {?function((boolean|undefined),!jspb.Message=): !Object} */ (
         null),
    0);

google_protobuf_descriptor_pb.MessageOptions.extensionsBinary[1037] = new jspb.ExtensionFieldBinaryInfo(
    proto.source,
    jspb.BinaryReader.prototype.readEnum,
    jspb.BinaryWriter.prototype.writeEnum,
    undefined,
    undefined,
    false);
// This registers the extension field with the extended class, so that
// toObject() will function correctly.
google_protobuf_descriptor_pb.MessageOptions.extensions[1037] = proto.source;


/**
 * A tuple of {field number, class constructor} for the extension
 * field named `ifdef`.
 * @type {!jspb.ExtensionFieldInfo<string>}
 */
proto.ifdef = new jspb.ExtensionFieldInfo(
    1038,
    {ifdef: 0},
    null,
     /** @type {?function((boolean|undefined),!jspb.Message=): !Object} */ (
         null),
    0);

google_protobuf_descriptor_pb.MessageOptions.extensionsBinary[1038] = new jspb.ExtensionFieldBinaryInfo(
    proto.ifdef,
    jspb.BinaryReader.prototype.readString,
    jspb.BinaryWriter.prototype.writeString,
    undefined,
    undefined,
    false);
// This registers the extension field with the extended class, so that
// toObject() will function correctly.
google_protobuf_descriptor_pb.MessageOptions.extensions[1038] = proto.ifdef;


/**
 * A tuple of {field number, class constructor} for the extension
 * field named `log`.
 * @type {!jspb.ExtensionFieldInfo<boolean>}
 */
proto.log = new jspb.ExtensionFieldInfo(
    1039,
    {log: 0},
    null,
     /** @type {?function((boolean|undefined),!jspb.Message=): !Object} */ (
         null),
    0);

google_protobuf_descriptor_pb.MessageOptions.extensionsBinary[1039] = new jspb.ExtensionFieldBinaryInfo(
    proto.log,
    jspb.BinaryReader.prototype.readBool,
    jspb.BinaryWriter.prototype.writeBool,
    undefined,
    undefined,
    false);
// This registers the extension field with the extended class, so that
// toObject() will function correctly.
google_protobuf_descriptor_pb.MessageOptions.extensions[1039] = proto.log;


/**
 * A tuple of {field number, class constructor} for the extension
 * field named `noDelay`.
 * @type {!jspb.ExtensionFieldInfo<boolean>}
 */
proto.noDelay = new jspb.ExtensionFieldInfo(
    1040,
    {noDelay: 0},
    null,
     /** @type {?function((boolean|undefined),!jspb.Message=): !Object} */ (
         null),
    0);

google_protobuf_descriptor_pb.MessageOptions.extensionsBinary[1040] = new jspb.ExtensionFieldBinaryInfo(
    proto.noDelay,
    jspb.BinaryReader.prototype.readBool,
    jspb.BinaryWriter.prototype.writeBool,
    undefined,
    undefined,
    false);
// This registers the extension field with the extended class, so that
// toObject() will function correctly.
google_protobuf_descriptor_pb.MessageOptions.extensions[1040] = proto.noDelay;

goog.object.extend(exports, proto);
